 
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/makeme/">MakeMe Site</a>
                    <span class="desktop-only">
                        <a class="item" href="http://goo.gl/ojHSM2">MakeMe News</a>
                        <a class="item" href="https://github.com/embedthis/me">Repository</a>
                        <a class="item" href="https://embedthis.com/blog/">Blog</a>
                        <a class="item" href="https://twitter.com/mobstream">Twitter</a>
                    </span>
