
                    <a class="item" href="https://www.embedthis.com/">Embedthis</a>
                    <a class="item" href="https://www.embedthis.com/makeme/">MakeMe Site</a>
                    <span class="desktop-only">
                        <a class="item" href="https://www.embedthis.com/blog/categories/MakeMe/">MakeMe News</a>
                        <a class="item" href="https://github.com/embedthis/me">Repository</a>
                        <a class="item" href="https://www.embedthis.com/blog/">Blog</a>
                        <a class="item" href="https://twitter.com/embedthat">Twitter</a>
                    </span>
